### ISSUE TITLE
doc install url wrong

### ISSUE THREAD

**Issue by onno-timmerman** [bigskysoftware/htmx-extensions#63] opened 2024-07-26 09:49 UTC
The docs say on https://unpkg.com/htmx-ext-class-tools@2.0.1/class-tools.js
But this is wrong and cannot be found

Cannot find package htmx-ext-class-tools@2.0.1

https://github.com/bigskysoftware/htmx-extensions/blob/main/src/class-tools/README.md#install

**Comment by Telroshan** [comment] 2024-07-26 11:01
Duplicate of #64, closing this one

**Closed by Telroshan** 2024-07-26 11:01 UTC
